In [1]:
import torch

In [64]:
a = torch.tensor(list(range(9)), dtype=torch.float32)
a

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [65]:
b = a.view(3,3)
b

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [66]:
c = b[1:, 1:]
"""
[[4,5], [7,8]] stride:(2, 1), shape=2x2
"""
c.stride()

(3, 1)

In [69]:
c.sin_()
b

tensor([[ 0.0000,  1.0000,  2.0000],
        [ 3.0000, -0.6339, -0.7302],
        [ 6.0000,  0.5735,  0.7417]])