In [5]:
import torch
import numpy as np
import re

In [34]:
with open("./book.txt", encoding="utf-8") as f:
    text = f.read().lower()

ascii_values = torch.tensor(list(text.encode("utf-8")))
ascii_values

tensor([42, 42, 42,  ..., 42, 42, 42])

In [36]:
text_onehot = torch.zeros(ascii_values.shape[0], 256, dtype=torch.bool)
text_onehot.scatter_(1, ascii_values.unsqueeze(-1).long(), True)

tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])

In [37]:
text = re.sub(r'[^\w\s]', '', text)
text = re.sub(r'\s+', ' ', text).strip()
words = text.split(' ')


In [38]:
words_list = sorted(set(words))
words2idx_dict = {word: i for (i,word) in enumerate(words_list)}

words2idx_dict


{'1': 0,
 '10': 1,
 '108': 2,
 '113': 3,
 '118': 4,
 '12': 5,
 '132': 6,
 '1342': 7,
 '139': 8,
 '143': 9,
 '146': 10,
 '148': 11,
 '15': 12,
 '154': 13,
 '156': 14,
 '161': 15,
 '166': 16,
 '168': 17,
 '175': 18,
 '177': 19,
 '1796': 20,
 '18': 21,
 '181': 22,
 '1813': 23,
 '189': 24,
 '1894': 25,
 '18th': 26,
 '194': 27,
 '198': 28,
 '2': 29,
 '200': 30,
 '209': 31,
 '211': 32,
 '213': 33,
 '215': 34,
 '22': 35,
 '221': 36,
 '225': 37,
 '228': 38,
 '235': 39,
 '24': 40,
 '243': 41,
 '253': 42,
 '256': 43,
 '26': 44,
 '261': 45,
 '263': 46,
 '267': 47,
 '26th': 48,
 '27': 49,
 '270': 50,
 '272': 51,
 '278': 52,
 '283': 53,
 '285': 54,
 '290': 55,
 '294': 56,
 '2_': 57,
 '301': 58,
 '31': 59,
 '318': 60,
 '321': 61,
 '327': 62,
 '334': 63,
 '339': 64,
 '345': 65,
 '34_': 66,
 '359': 67,
 '36': 68,
 '363': 69,
 '368': 70,
 '370': 71,
 '377': 72,
 '385': 73,
 '393': 74,
 '4': 75,
 '40': 76,
 '404': 77,
 '415': 78,
 '420': 79,
 '422': 80,
 '43': 81,
 '431': 82,
 '434': 83,
 '442': 84,
 '4

In [40]:
text_onehot_word = torch.zeros(len(words), len(words2idx_dict), dtype=torch.bool)
for i, word in enumerate(words):
    text_onehot_word[i][words2idx_dict[word]] = True

text_onehot_word

tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])

In [42]:
text_onehot_word.shape

torch.Size([127319, 8604])