In [474]:
import torch
import numpy as np

In [475]:
dir = "./data/timeSeries/hour-fixed.csv"

In [476]:
data_np = np.loadtxt(dir, dtype=np.float32, delimiter=",", skiprows=1, converters={1: lambda x: float(x[8:10])})
bikes = torch.from_numpy(data_np)

In [477]:
daily_weather = bikes.view(-1, 24, bikes.shape[1])
daily_weather.transpose_(1,2)

tensor([[[1.0000e+00, 2.0000e+00, 3.0000e+00,  ..., 2.2000e+01,
          2.3000e+01, 2.4000e+01],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         ...,
         [3.0000e+00, 8.0000e+00, 5.0000e+00,  ..., 3.0000e+00,
          1.1000e+01, 1.5000e+01],
         [1.3000e+01, 3.2000e+01, 2.7000e+01,  ..., 3.1000e+01,
          1.7000e+01, 2.4000e+01],
         [1.6000e+01, 4.0000e+01, 3.2000e+01,  ..., 3.4000e+01,
          2.8000e+01, 3.9000e+01]],

        [[2.5000e+01, 2.6000e+01, 2.7000e+01,  ..., 4.5000e+01,
          4.6000e+01, 4.7000e+01],
         [2.0000e+00, 2.0000e+00, 2.0000e+00,  ..., 2.0000e+00,
          2.0000e+00, 2.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         ...,
         [4.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.1000e+01,
          0.000

In [486]:
first_day = bikes[:24].long()

weather_onehot = torch.zeros(first_day.shape[0], 4, dtype=torch.int64)
weather_onehot.scatter_(dim=1, index=first_day[:,9].unsqueeze(1).long()- 1,value=1.0)
weather_onehot

tensor([[1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0]])

In [479]:
t = torch.cat((bikes[:24], weather_onehot), 1)

In [492]:
daily_weather[:, 9, :] = (daily_weather[:, 9, :]- 1.0) / 3.0
daily_weather[9]

tensor([[ 2.1000e+02,  2.1100e+02,  2.1200e+02,  2.1300e+02,  2.1400e+02,
          2.1500e+02,  2.1600e+02,  2.1700e+02,  2.1800e+02,  2.1900e+02,
          2.2000e+02,  2.2100e+02,  2.2200e+02,  2.2300e+02,  2.2400e+02,
          2.2500e+02,  2.2600e+02,  2.2700e+02,  2.2800e+02,  2.2900e+02,
          2.3000e+02,  2.3100e+02,  2.3200e+02,  2.3300e+02],
        [ 1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,
          1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,
          1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,
          1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01,
          1.0000e+01,  1.0000e+01,  1.0000e+01,  1.0000e+01],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  